version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          command: ./gradlew :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

