name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repo stuff
      uses: actions/checkout@v2
      
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
   
    - name: Lint check
      run: ./gradlew lint
    
    - name: Upload lint report
      uses: actions/upload-artifact@v1
      with:
        name: LintReports
        path: app/build/reports/
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: DebugAPK
        path: app/build/outputs/apk/debug/
        
